# pyproject.toml
[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F","W", "I", "UP", "B"] # Select rules to check
ignore = ["E501", "B028", "B904"]


# [tool.mypy]
# python_version = "3.10"
# warn_return_any = false
# warn_unused_configs = true
# disallow_untyped_defs = false
# disallow_incomplete_defs = false
# check_untyped_defs = false
# ignore_missing_imports = true
# strict_optional = false
# pretty = true
